### ISSUE TITLE
Where to get deis socks?

### ISSUE THREAD

**Issue by Cryptophobia** [Codaisseur/alea#17]
This is a really serious non-technical issue but where did you get those deis socks? 😆

**Comment by wearethefoos** [comment]
Worksforme. :trollface: 

I opened an issue here in deis/workflow#831

**Comment by squillace** [comment]
@Cryptophobia we may have tracked down some remaining few. So, to whom does @karenchu talk to? :-)

**Comment by Cryptophobia** [comment]
@squillace : If @foxycoder  does not need any more of the socks, I will take them. 🎁  🎅  👶  Let me know where to send you some $ for the shipping.
