### ISSUE TITLE
Recreate Postgres Cluster based on Stolon

### ISSUE THREAD

**Issue by wearethefoos** [Codaisseur/alea#9]
Replace the current Postgres+Pgpool-II setup with Stolon.

### Some Background, Rationale

The current setup with pgpool does not work. When we create new postgres users for apps in the Services API, pgpool-II does not know about them and connection attempts with these new users fail with:

```
ERROR:  "MD5" authentication with pgpool failed for user XXX
```

We've used [Stolon][stolon] previously, and with success. However, with Stolon we are limited to just 100 client connections, hence the decision to use pgpool-II for connection pooling. With the headaches above as a result.

So, back to Stolon seems the most viable option right now. If we run out of connection slots, we could set up additional Stolon clusters in the future and link the Services API to that new one so it will start giving out databases and users on that new cluster. - Let's make that nice-to-have for now though.

[stolon]: https://github.com/sorintlab/stolon/tree/master/examples/kubernetes

**Comment by michfarr** [comment]
PR opened: #10
